model:
  label_aspects: ["Price fairness", "Data availability",
    "Cleanliness", "Punctuality", "Facilities", "Accessibility",
    "Satisfactions", "Staff service", "Safety", "Others"]

  labels: ["Price fairness", "Cleanliness", "Facilities", "Staff quality", "Convenience",
    "Punctuality", "Accessibility", "Safety", "Data availability"]

  # label polarity
  label_polarity: ["positive", "negative", "neutral"]

  # using LLM
  llm:
    type: ???
    name: ???

  style: "ate"

  pretrained:
    name: ???
    freeze: ??? # freeze model for finetuning or training

  train:
    # train paramters
    out_dir: ???
    epochs: 8
    batch_size: 8
    train_dir: ???
    log_steps: 100
    lr: 2e-4
    weight_decay: 0.01
    warmup_step: 500
