model:
 # using LLM
 llm:
  gemini: True
  name: ???

 # using pretrained model for fine tuning
 pretrained:
  bert: True
  name: ???
  freeze: ??? # freeze model for finetuning or training

 vocab:
  dir: ???

 train:
 # train paramters
  epoch: 50
  batch_size: 8