model:
 label_aspects: ["Price fairness", "Data availability", 
 "Cleanliness", "Punctuality", "Facilities", "Accessibility", 
 "Satisfactions", "Staff service", "Safety", "Others"]
 
 # label polarity
 label_polarity: ["positive", "negative", "neutral"]

 # using LLM
 llm:
  type: ???
  name: ???

 style: "ate"

 # using pretrained model for fine tuning
 pretrained:
  bert: True
  name: "yangheng/deberta-v3-base-absa-v1.1"
  freeze: ??? # freeze model for finetuning or training

 train:
  # train paramters
  out_dir: ???
  epoch: 8
  batch_size: 8
  train_dir: ???
  log_dir: ???
  log_strategy: "steps"
  log_steps: 100
  lr: 2e-4
  weight_decay: 0.01
  warmup_step: 500
  report_to: "wandb"
  push_to_hub: True
  hub_strategy: "every_save"
  hub_model_id: ??? # setup
  hub_token: ??? # setup