model:
 # label aspects
 label_aspects: ["Safety", "Cleanliness", "Data availability",
                 "Price fairness", "Satisfactions",
                 "Facilities", "Maintenance",
                 "Punctuality", "Accessibility",
                 "Others", "Staff service"]
 
 # label polarity
 label_polarity: ["positive", "negative", "neutral"]

 # using LLM
 llm:
  type: ???
  name: ???
 style: "ate"
 # using pretrained model for fine tuning
 pretrained:
  bert: True
  name: "yangheng/deberta-v3-base-absa-v1.1"
  freeze: ??? # freeze model for finetuning or training

 train:
 # train paramters
  epoch: 50
  batch_size: 8
  train_dir: ???