model:
 # common config
 common:
  load_in_4bit: True
  torch_dtype: ??? # float16 || bfloat16
  use_cache: False
  
 # model config
 model_name: ???

 # label aspects
 label_aspects: ["Safety", "Cleanliness", "Data availability", "Price fairness", 
 "User-friendly payment system", "Handling complaints", "Satisfactions", "Facilities at station", 
 "Facilities within train", "Accessibility for disabilities", "Maintenance", 
 "Punctuality", "Ease of connections between lines", "Reliability equipment", 
 "Accidents", "Others"]
 
 # label polarity
 label_polarities: ["positive", "negative", "neutral"]

 # instruction style
 instruction_style: simple # multi-task or simple

 # bit and bytes config
 bitandbytes_config:
  bnb_4bit_compute_dtype: ???
  bnb_4bit_quant_type: ???
  bnb_4bit_use_double_quant: ???

  # peft config
  peft_config:
   alpha: ???
   lora_dropout: ???
   peft_r: ???
   peft_bias: ???
   task_type: ???

 # train parameters
 train:
  epoch:
  batch:
  lr:
  optimizer: